name: Code Review Suggestions

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.jsx'

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install axios

    - name: Review JavaScript/JSX Files (Excluding node_modules)
      run: |
        # Find all .js and .jsx files, excluding node_modules directory
        find . -name "*.js" -or -name "*.jsx" -not -path "*/node_modules/*" > files_to_review.txt

        FILES=()
        while IFS= read -r file; do
          FILES+=("$file")
        done < files_to_review.txt

        # Process files in parallel
        for file in "${FILES[@]}"; do
          echo "Reviewing file: $file"
          FILE_CONTENT=$(cat "$file")
          echo "$FILE_CONTENT" > file_to_review.txt

          # Run Node.js script for parallel execution
          node analyze-diff.js "$file" &
        done
        wait

    - name: Post Review Comments to PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          $(cat pr_comments.md)
