name: Code Review Suggestions

on:
  pull_request:
    paths:
      - 'app/**/*.js'   # Only includes .js files in the app folder
      - 'app/**/*.jsx'  # Only includes .jsx files in the app folder

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install axios

    - name: Review JavaScript/JSX Files in App Folder
      run: |
        # Find all .js and .jsx files under the app folder
        find app -name "*.js" -or -name "*.jsx" > files_to_review.txt
        
        FILES=()
        while IFS= read -r file; do
          FILES+=("$file")
        done < files_to_review.txt

        # Process files in parallel
        for file in "${FILES[@]}"; do
          echo "Reviewing file: $file"
          FILE_CONTENT=$(cat "$file")
          echo "$FILE_CONTENT" > file_to_review.txt

          # Run Node.js script for parallel execution
          node analyze-diff.js "$file" &
        done
        wait

    - name: Post Review Comments to PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          $(cat pr_comments.md)
