name: PR Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review_code:
    name: Review PR Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: app/**/*.js, app/**/*.jsx

      - name: Analyze Code with OpenAI
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Reviewing changed files..."
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Reviewing file: $file"

            # Read file content
            CONTENT=$(cat "$file" | base64)

            # Call OpenAI API for code review
            RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{
                "model": "gpt-4",
                "messages": [
                  {"role": "system", "content": "You are a code reviewer. Find logical, security, and performance defects in the following JavaScript/React code and suggest improvements."},
                  {"role": "user", "content": "'"$(echo "$CONTENT" | base64 --decode)"'"}
                ],
                "temperature": 0.2
              }')

            # Extract AI response
            COMMENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

            # Post comment in PR
            if [[ ! -z "$COMMENT" ]]; then
              gh pr comment ${{ github.event.pull_request.number }} -b "**Code Review ($file):**\n$COMMENT"
            fi
          done
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
