name: Code Review Suggestions

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch, or change it to your preferred branch.
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.jsx'

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install axios

    - name: Collect All JavaScript and JSX Files
      id: collect_files
      run: |
        # Find all .js and .jsx files and save them in a list
        find . -name "*.js" -or -name "*.jsx" > files_to_review.txt

    - name: Review Each File Separately
      run: |
        # For each file, send its content for review
        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            echo "Reviewing file: $file"

            # Read the file content
            FILE_CONTENT=$(cat "$file")
            
            # Save the file content to a temporary file for analysis
            echo "$FILE_CONTENT" > file_to_review.txt

            # Run the Node.js script to analyze the file content
            node analyze-diff.js

            # Post review suggestions as PR comment
            COMMENT=$(cat code-review-suggestions.txt)
            if [[ -n "$COMMENT" ]]; then
              echo "Posting comment for file: $file"
              echo "## Code Review Suggestions for $file" >> pr_comments.md
              echo "```txt" >> pr_comments.md
              echo "$COMMENT" >> pr_comments.md
              echo "```" >> pr_comments.md
              echo "" >> pr_comments.md
            fi
          fi
        done < files_to_review.txt

    - name: Post All Review Comments as PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          $(cat pr_comments.md)
