name: Code Review Suggestions

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.jsx'

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install axios

    - name: Review JavaScript/JSX Files
      run: |
        # Find all .js and .jsx files and review them using OpenAI
        find . -name "*.js" -or -name "*.jsx" > files_to_review.txt
        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            echo "Reviewing file: $file"
            FILE_CONTENT=$(cat "$file")
            echo "$FILE_CONTENT" > file_to_review.txt

            # Run Node.js script to get review suggestions
            node analyze-diff.js

            # Post review suggestions as PR comment
            COMMENT=$(cat code-review-suggestions.txt)
            if [[ -n "$COMMENT" ]]; then
              echo "Posting comment for file: $file"
              echo "## Code Review Suggestions for $file" >> pr_comments.md
              echo "```txt" >> pr_comments.md
              echo "$COMMENT" >> pr_comments.md
              echo "```" >> pr_comments.md
              echo "" >> pr_comments.md
            fi
          fi
        done < files_to_review.txt

    - name: Post Review Comments to PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          $(cat pr_comments.md)
